# Generated by Django 5.0.7 on 2024-08-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
