# Generated by Django 5.0.7 on 2024-08-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='rating_count',
            new_name='rating_cou',
        ),
    ]
