# Generated by Django 5.0.7 on 2024-08-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
