# Generated by Django 5.0.7 on 2024-08-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_products_rating_products_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
