# Generated by Django 5.0.7 on 2024-08-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_rating_count_products_rating_cou'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='rating_cou',
            new_name='average_rating',
        ),
    ]
